# Generated by Django 3.0.5 on 2021-03-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('usuario', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='ident',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='ident',
        ),
    ]
