# Generated by Django 3.0.5 on 2021-03-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0002_auto_20210307_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(max_length=20),
        ),
    ]
